'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3082
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Runtime.Serialization

Namespace Activelock36Service
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LicFlags", [Namespace]:="http://tempuri.org/")>  _
    Public Enum LicFlags As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        alfSingle = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        alfMulti = 1
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ALLicType", [Namespace]:="http://tempuri.org/")>  _
    Public Enum ALLicType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        allicNone = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        allicPeriodic = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        allicPermanent = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        allicTimeLocked = 3
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Activelock36Service.Activelock3_6ServiceSoap")>  _
    Public Interface Activelock3_6ServiceSoap
        
        'CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorld(ByVal request As Activelock36Service.HelloWorldRequest) As Activelock36Service.HelloWorldResponse
        
        'CODEGEN: Generating message contract since element name pInstallCode from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTrial", ReplyAction:="*")>  _
        Function GetTrial(ByVal request As Activelock36Service.GetTrialRequest) As Activelock36Service.GetTrialResponse
        
        'CODEGEN: Generating message contract since element name pInstallCode from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetLicense", ReplyAction:="*")>  _
        Function GetLicense(ByVal request As Activelock36Service.GetLicenseRequest) As Activelock36Service.GetLicenseResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorld", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Activelock36Service.HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Activelock36Service.HelloWorldRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorldResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Activelock36Service.HelloWorldResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Activelock36Service.HelloWorldResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HelloWorldResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public HelloWorldResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HelloWorldResult As String)
            MyBase.New
            Me.HelloWorldResult = HelloWorldResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTrialRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTrial", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Activelock36Service.GetTrialRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Activelock36Service.GetTrialRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetTrialRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public pInstallCode As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public pSoftwareName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public pSoftwareVersion As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pInstallCode As String, ByVal pSoftwareName As String, ByVal pSoftwareVersion As String)
            MyBase.New
            Me.pInstallCode = pInstallCode
            Me.pSoftwareName = pSoftwareName
            Me.pSoftwareVersion = pSoftwareVersion
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTrialResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTrialResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Activelock36Service.GetTrialResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Activelock36Service.GetTrialResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetTrialResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetTrialResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetTrialResult As String)
            MyBase.New
            Me.GetTrialResult = GetTrialResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetLicenseRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetLicense", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Activelock36Service.GetLicenseRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Activelock36Service.GetLicenseRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetLicenseRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public pInstallCode As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public pSoftwareName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public pSoftwareVersion As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public pRegisteredLevel As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public networkLicense As Activelock36Service.LicFlags
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public maximumUsers As Short
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public mLicType As Activelock36Service.ALLicType
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public mDays As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pInstallCode As String, ByVal pSoftwareName As String, ByVal pSoftwareVersion As String, ByVal pRegisteredLevel As String, ByVal networkLicense As Activelock36Service.LicFlags, ByVal maximumUsers As Short, ByVal mLicType As Activelock36Service.ALLicType, ByVal mDays As String)
            MyBase.New
            Me.pInstallCode = pInstallCode
            Me.pSoftwareName = pSoftwareName
            Me.pSoftwareVersion = pSoftwareVersion
            Me.pRegisteredLevel = pRegisteredLevel
            Me.networkLicense = networkLicense
            Me.maximumUsers = maximumUsers
            Me.mLicType = mLicType
            Me.mDays = mDays
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetLicenseResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetLicenseResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Activelock36Service.GetLicenseResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Activelock36Service.GetLicenseResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetLicenseResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetLicenseResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetLicenseResult As String)
            MyBase.New
            Me.GetLicenseResult = GetLicenseResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface Activelock3_6ServiceSoapChannel
        Inherits Activelock36Service.Activelock3_6ServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class Activelock3_6ServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of Activelock36Service.Activelock3_6ServiceSoap)
        Implements Activelock36Service.Activelock3_6ServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Activelock36Service_Activelock3_6ServiceSoap_HelloWorld(ByVal request As Activelock36Service.HelloWorldRequest) As Activelock36Service.HelloWorldResponse Implements Activelock36Service.Activelock3_6ServiceSoap.HelloWorld
            Return MyBase.Channel.HelloWorld(request)
        End Function
        
        Public Function HelloWorld() As String
            Dim inValue As Activelock36Service.HelloWorldRequest = New Activelock36Service.HelloWorldRequest
            inValue.Body = New Activelock36Service.HelloWorldRequestBody
            Dim retVal As Activelock36Service.HelloWorldResponse = CType(Me,Activelock36Service.Activelock3_6ServiceSoap).HelloWorld(inValue)
            Return retVal.Body.HelloWorldResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Activelock36Service_Activelock3_6ServiceSoap_GetTrial(ByVal request As Activelock36Service.GetTrialRequest) As Activelock36Service.GetTrialResponse Implements Activelock36Service.Activelock3_6ServiceSoap.GetTrial
            Return MyBase.Channel.GetTrial(request)
        End Function
        
        Public Function GetTrial(ByVal pInstallCode As String, ByVal pSoftwareName As String, ByVal pSoftwareVersion As String) As String
            Dim inValue As Activelock36Service.GetTrialRequest = New Activelock36Service.GetTrialRequest
            inValue.Body = New Activelock36Service.GetTrialRequestBody
            inValue.Body.pInstallCode = pInstallCode
            inValue.Body.pSoftwareName = pSoftwareName
            inValue.Body.pSoftwareVersion = pSoftwareVersion
            Dim retVal As Activelock36Service.GetTrialResponse = CType(Me,Activelock36Service.Activelock3_6ServiceSoap).GetTrial(inValue)
            Return retVal.Body.GetTrialResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Activelock36Service_Activelock3_6ServiceSoap_GetLicense(ByVal request As Activelock36Service.GetLicenseRequest) As Activelock36Service.GetLicenseResponse Implements Activelock36Service.Activelock3_6ServiceSoap.GetLicense
            Return MyBase.Channel.GetLicense(request)
        End Function
        
        Public Function GetLicense(ByVal pInstallCode As String, ByVal pSoftwareName As String, ByVal pSoftwareVersion As String, ByVal pRegisteredLevel As String, ByVal networkLicense As Activelock36Service.LicFlags, ByVal maximumUsers As Short, ByVal mLicType As Activelock36Service.ALLicType, ByVal mDays As String) As String
            Dim inValue As Activelock36Service.GetLicenseRequest = New Activelock36Service.GetLicenseRequest
            inValue.Body = New Activelock36Service.GetLicenseRequestBody
            inValue.Body.pInstallCode = pInstallCode
            inValue.Body.pSoftwareName = pSoftwareName
            inValue.Body.pSoftwareVersion = pSoftwareVersion
            inValue.Body.pRegisteredLevel = pRegisteredLevel
            inValue.Body.networkLicense = networkLicense
            inValue.Body.maximumUsers = maximumUsers
            inValue.Body.mLicType = mLicType
            inValue.Body.mDays = mDays
            Dim retVal As Activelock36Service.GetLicenseResponse = CType(Me,Activelock36Service.Activelock3_6ServiceSoap).GetLicense(inValue)
            Return retVal.Body.GetLicenseResult
        End Function
    End Class
End Namespace
