'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ActiveLockWizard.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property ActivelockWizrd() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ActivelockWizrd", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property small_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;********************************************************************************&apos;
        '''&apos;*   ActiveLock                                                                 *&apos;
        '''&apos;*   Copyright 1998-2002 Nelson Ferraz                                          *&apos;
        '''&apos;*   Copyright 2003-2007 The ActiveLock Software Group (ASG)                    *&apos;
        '''&apos;*   All material is the property of the contributing authors.                  *&apos;
        '''&apos;*                                                                              *&apos;
        '''&apos;*   Red [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property VB2005FormHeader() As String
            Get
                Return ResourceManager.GetString("VB2005FormHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''    Public Function VerifyActiveLockNETdll() As String
        '''        &apos; CRC32 Hash...
        '''        &apos; I have modified this routine to read the crc32
        '''        &apos; of the Activelock3NET.dll directly
        '''        &apos; since the assembly is not a COM object anymore
        '''        &apos; the method below is very suitable for .NET and more appropriate
        '''        Dim c As New CRC32
        '''        Dim crc As Integer = 0
        '''        Dim fileName As String = System.Windows.Forms.Application.StartupPath &amp; &quot;\ActiveLock3_5NET.dll&quot;
        '''        If File.Exists(file [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property VB2005FormRoutines() As String
            Get
                Return ResourceManager.GetString("VB2005FormRoutines", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''Option Strict Off
        '''Imports ActiveLock3_5NET
        '''Imports System.IO
        '''Imports Microsoft.VisualBasic.FileSystem
        '''Imports VB = Microsoft.VisualBasic.Strings
        '''Imports Microsoft.VisualBasic.Compatibility
        '''
        '''Module modActiveLockVb2005
        '''
        '''    Public Structure ActivelockValues_t
        '''        Public RegStatus As String
        '''        Public UsedDaysOrRuns As String
        '''        Public ValidTrial As Boolean
        '''        Public LicenceType As String
        '''        Public ExpirationDate As String
        '''        Public RegisteredUser As String
        '''        [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property VB2005FormTop() As String
            Get
                Return ResourceManager.GetString("VB2005FormTop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;********************************************************************************&apos;
        '''&apos;*   ActiveLock                                                                 *&apos;
        '''&apos;*   Copyright 1998-2002 Nelson Ferraz                                          *&apos;
        '''&apos;*   Copyright 2003-2007 The ActiveLock Software Group (ASG)                    *&apos;
        '''&apos;*   All material is the property of the contributing authors.                  *&apos;
        '''&apos;*                                                                              *&apos;
        '''&apos;*   Red [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property VB6FormHeader() As String
            Get
                Return ResourceManager.GetString("VB6FormHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Function CheckForResources(ParamArray MyArray()) As Boolean
        '''&apos;MyArray is a list of things to check
        '''&apos;These can be DLLs or OCXs
        '''
        '''&apos;Files, by default, are searched for in the Windows System Directory
        '''&apos;Exceptions;
        '''&apos;   Begins with a # means it should be in the same directory with the executable
        '''&apos;   Contains the full path (anything with a &quot;\&quot;)
        '''
        '''&apos;Typical names would be &quot;#aaa.dll&quot;, &quot;mydll.dll&quot;, &quot;myocx.ocx&quot;, &quot;comdlg32.ocx&quot;, &quot;mscomctl.ocx&quot;, &quot;msflxgrd.ocx&quot;
        '''
        '''&apos;If the file has no extension, we;
        '''&apos;     assume it&apos; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property VB6FormRoutines() As String
            Get
                Return ResourceManager.GetString("VB6FormRoutines", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attribute VB_Name = &quot;modALVB6&quot;
        '''   
        '''   Type ActivelockValues_t
        '''         RegStatus As String
        '''         UsedDaysOrRuns As String
        '''         ValidTrial As Boolean
        '''         LicenceType As String
        '''         ExpirationDate As String
        '''         RegisteredUser As String
        '''         RegisteredLevel As String
        '''         LicenseClass As String
        '''         MaxCount As Integer
        '''End Type
        '''
        '''Private Declare Function MapFileAndCheckSum Lib &quot;imagehlp&quot; Alias &quot;MapFileAndCheckSumA&quot; (ByVal FileName As String, HeaderSum As Long, Chec [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property VB6FormTop() As String
            Get
                Return ResourceManager.GetString("VB6FormTop", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
