Module modVB2005
    Dim TheFileName As String = "modALVB2005.vb"
    Dim FilePath As String = Nothing
    Public Sub CreateVB2005Module()
        Dim MyDialogResult As DialogResult
        frmMain.FolderBrowserDialog.SelectedPath = Application.StartupPath
        frmMain.FolderBrowserDialog.Description = "Please Select a folder To Save The File To"
        MyDialogResult = frmMain.FolderBrowserDialog.ShowDialog
        If MyDialogResult = Windows.Forms.DialogResult.OK Then
            FilePath = frmMain.FolderBrowserDialog.SelectedPath
        Else
            MsgBox("You Have To Select A Folder To Save The File To First", MsgBoxStyle.Critical)
            Exit Sub
        End If
        CreateFile()
        WriteToFile(My.Resources.VB2005FormHeader)
        WriteToFile(My.Resources.VB2005FormTop)
        CreateRoutineInitActivelock()
        WriteToFile(My.Resources.VB2005FormRoutines)
        MsgBox("File Created Successfully, The New FileName Is: " & TheFileName, MsgBoxStyle.Information)
    End Sub
    Private Sub CreateFile()
        My.Computer.FileSystem.WriteAllText(FilePath & "\" & TheFileName, String.Empty, False)
    End Sub
    Private Sub WriteToFile(ByVal Data As String)
        My.Computer.FileSystem.WriteAllText(FilePath & "\" & TheFileName, Data, True)
    End Sub
    Private Sub CreateRoutineInitActivelock()
        WriteToFile("Private Const CrcDataEnc As String = " & Chr(34) & CrcDataEnc & Chr(34) & vbCrLf) 'added
        WriteToFile("Private Const PUB_KEY as string = " & Chr(34) & Enc(SoftwareCode) & Chr(34) & vbCrLf)
        WriteToFile("#End Region '" & Chr(34) & "Local Declare" & Chr(34) & vbCrLf)
        WriteToFile(vbCrLf)
        WriteToFile("#Region " & Chr(34) & "Global Routines" & Chr(34) & vbCrLf)
        WriteToFile(vbCrLf)
        WriteToFile("    'This Routine Starts The Protection Of Your Software" & vbCrLf)
        WriteToFile("    Public Function InitActivelock() As Boolean" & vbCrLf)
        WriteToFile("        Dim MyAL As New ActiveLock3_6NET.Globals" & vbCrLf)
        WriteToFile("        Dim strAutoRegisterKeyPath As String" & vbCrLf)
        WriteToFile("        Dim boolAutoRegisterKeyPath As Boolean" & vbCrLf)
        WriteToFile("        Dim strMsg As String = Nothing" & vbCrLf)
        WriteToFile("        Dim A() As String" & vbCrLf)
        WriteToFile("        On Error GoTo NotRegistered" & vbCrLf)
        WriteToFile("        'CheckForResources(" & Chr(34) & "comctl32.ocx" & Chr(34) & ", " & Chr(34) & "tabctl32.ocx" & Chr(34) & ")" & vbCrLf)
        WriteToFile("        MyActiveLock = MyAL.NewInstance()" & vbCrLf)
        WriteToFile("        With MyActiveLock" & vbCrLf)
        WriteToFile("             .SoftwareName = " & Chr(34) & SoftwareName & Chr(34) & vbCrLf)
        WriteToFile("             .SoftwareVersion = " & Chr(34) & SoftwareVersion & Chr(34) & vbCrLf)
        WriteToFile("             .SoftwarePassword = " & EncodedPassword(SoftwarePassword) & vbCrLf)
        WriteToFile("             .LicenseKeyType = ActiveLock3_6NET.IActiveLock.ALLicenseKeyTypes." & LicenceKeyType.ToString & vbCrLf)
        WriteToFile("             .TrialType = ActiveLock3_6NET.IActiveLock.ALTrialTypes." & TrialType.ToString & vbCrLf)
        If TrialType <> TrialType_t.trialNone Then
            WriteToFile("             .TrialLength = " & TrialLength.ToString & vbCrLf)
            WriteToFile("             .TrialHideType = " & GetHideTypeString(TrialHideType) & vbCrLf)
        End If
        WriteToFile("             .SoftwareCode = Dec(PUB_KEY)" & vbCrLf)
        WriteToFile("             .LockType = " & GetLockTypesString(LockTypes) & vbCrLf)
        WriteToFile("             .AutoRegister = ActiveLock3_6NET.IActiveLock.ALAutoRegisterTypes." & AutoRegister.ToString & vbCrLf)
        WriteToFile("             strAutoRegisterKeyPath = AppPath() & " & Chr(34) & "\" & Chr(34) & " & .SoftwareName & " & Chr(34) & ".all" & Chr(34) & vbCrLf)
        WriteToFile("             .AutoRegisterKeyPath = strAutoRegisterKeyPath" & vbCrLf)
        WriteToFile("             If File.Exists(strAutoRegisterKeyPath) Then boolAutoRegisterKeyPath = True" & vbCrLf)
        WriteToFile("             .CheckTimeServerForClockTampering = ActiveLock3_6NET.IActiveLock.ALTimeServerTypes." & TimeServerClockTampering.ToString & vbCrLf)
        WriteToFile("             .CheckSystemFilesForClockTampering = ActiveLock3_6NET.IActiveLock.ALSystemFilesTypes." & SystemFilesClockTampering.ToString & vbCrLf)
        WriteToFile("             .LicenseFileType = ActiveLock3_6NET.IActiveLock.ALLicenseFileTypes." & LicenceFileType.ToString & vbCrLf)
        WriteToFile("             VerifyActiveLockNETdll()" & vbCrLf)
        WriteToFile("             .KeyStoreType = ActiveLock3_6NET.IActiveLock.LicStoreType." & KeyStoreType.ToString & vbCrLf)
        WriteToFile("             strKeyStorePath = AppPath() & " & Chr(34) & "\" & Chr(34) & " & .SoftwareName & " & Chr(34) & ".lic" & Chr(34) & vbCrLf)
        WriteToFile("             .KeyStorePath = strKeyStorePath" & vbCrLf)
        WriteToFile("             ActiveLockEventSink = .EventNotifier" & vbCrLf)
        WriteToFile("             'Use the following with ASP.NET applications" & vbCrLf)
        WriteToFile("             'MyActiveLock.Init(Application.StartupPath & " & Chr(34) & "\bin" & Chr(34) & ")" & vbCrLf)
        WriteToFile("             'Use the following with VB.NET applications" & vbCrLf)
        WriteToFile("             '.Init()" & vbCrLf)
        WriteToFile("             'Or if alcrypto3NET.dll is the same directory" & vbCrLf)
        WriteToFile("             .Init(Application.StartupPath, strKeyStorePath)" & vbCrLf)
        WriteToFile("             Dim strRemainingTrialDays As String = Nothing" & vbCrLf)
        WriteToFile("             Dim strRemainingTrialRuns As String = Nothing" & vbCrLf)
        WriteToFile("             Dim strTrialLength As String = Nothing" & vbCrLf)
        WriteToFile("             Dim strUsedDays As String = Nothing" & vbCrLf)
        WriteToFile("             Dim strExpirationDate As String = Nothing" & vbCrLf)
        WriteToFile("             Dim strRegisteredUser As String = Nothing" & vbCrLf)
        WriteToFile("             Dim strRegisteredLevel As String = Nothing" & vbCrLf)
        WriteToFile("             Dim strLicenseClass As String = Nothing" & vbCrLf)
        WriteToFile("             Dim strMaxCount As String = Nothing" & vbCrLf)
        WriteToFile("             Dim strLicenseFileType As String = Nothing" & vbCrLf)
        WriteToFile("             Dim strLicenseType As String = Nothing" & vbCrLf)
        WriteToFile("             Dim strUsedLockType As String = Nothing" & vbCrLf)
        WriteToFile("             .Acquire(strMsg, strRemainingTrialDays, strRemainingTrialRuns, strTrialLength, strUsedDays, strExpirationDate, strRegisteredUser, strRegisteredLevel, strLicenseClass, strMaxCount, strLicenseFileType, strLicenseType, strUsedLockType)" & vbCrLf)
        WriteToFile("             If strMsg <> " & Chr(34) & Chr(34) & " Then 'There's a trial" & vbCrLf)
        WriteToFile("                 A = Split(strMsg, vbCrLf)" & vbCrLf)
        WriteToFile("                 ActivelockValues.RegStatus = A(0)" & vbCrLf)
        WriteToFile("                 ActivelockValues.UsedDaysOrRuns = A(1)" & vbCrLf)
        WriteToFile("                 ActivelockValues.ValidTrial = True" & vbCrLf)
        WriteToFile("                 ActivelockValues.LicenceType = " & Chr(34) & "Free Trial" & Chr(34) & vbCrLf)
        WriteToFile("                 Return True" & vbCrLf)
        WriteToFile("             Else" & vbCrLf)
        WriteToFile("                 ActivelockValues.ValidTrial = False" & vbCrLf)
        WriteToFile("                 ActivelockValues.LicenceType = " & Chr(34) & "No Trial" & Chr(34) & vbCrLf)
        WriteToFile("             End If" & vbCrLf)
        WriteToFile("             ActivelockValues.LicenceType = " & Chr(34) & "Registered" & Chr(34) & vbCrLf)
        WriteToFile("             ActivelockValues.UsedDaysOrRuns = strUsedDays" & vbCrLf)
        WriteToFile("             ActivelockValues.ExpirationDate = strExpirationDate" & vbCrLf)
        WriteToFile("             If ActivelockValues.ExpirationDate = " & Chr(34) & Chr(34) & " Then ActivelockValues.ExpirationDate = " & Chr(34) & "Permanent" & Chr(34) & vbCrLf)
        WriteToFile("             ActivelockValues.RegisteredUser = .RegisteredUser" & vbCrLf)
        WriteToFile("             ActivelockValues.AppName = MyActiveLock.SoftwareName" & vbCrLf)
        WriteToFile("             ActivelockValues.AppVersion = MyActiveLock.SoftwareVersion" & vbCrLf)
        WriteToFile("             ActivelockValues.RegisteredLevel = strRegisteredLevel" & vbCrLf)
        WriteToFile("             ' Networked Licenses" & vbCrLf)
        WriteToFile("             If strLicenseClass = LicFlags.alfMulti Then" & vbCrLf)
        WriteToFile("                 ActivelockValues.LicenseClass = " & Chr(34) & "Networked" & Chr(34) & vbCrLf)
        WriteToFile("             Else 'If strLicenseType = LicFlags.alfSingle Then" & vbCrLf)
        WriteToFile("                 ActivelockValues.LicenseClass = " & Chr(34) & "Single User" & Chr(34) & vbCrLf)
        WriteToFile("             End If" & vbCrLf)
        WriteToFile("             ActivelockValues.MaxCount = strMaxCount" & vbCrLf)
        WriteToFile("             'determine the license type" & vbCrLf)
        WriteToFile("             If strLicenseType = " & Chr(34) & "allicTimeLocked" & Chr(34) & " Then" & vbCrLf)
        WriteToFile("                 ActivelockValues.LicenceType = " & Chr(34) & "Time Limited" & Chr(34) & vbCrLf)
        WriteToFile("             ElseIf strLicenseType = " & Chr(34) & "allicPeriodic" & Chr(34) & " Then" & vbCrLf)
        WriteToFile("                 ActivelockValues.LicenceType = " & Chr(34) & "Periodic" & Chr(34) & vbCrLf)
        WriteToFile("             ElseIf strLicenseType = " & Chr(34) & "allicPermanent" & Chr(34) & " Then" & vbCrLf)
        WriteToFile("                 ActivelockValues.LicenceType = " & Chr(34) & "Permanent" & Chr(34) & vbCrLf)
        WriteToFile("             Else" & vbCrLf)
        WriteToFile("                 ActivelockValues.LicenceType = " & Chr(34) & "None" & Chr(34) & vbCrLf)
        WriteToFile("             End If" & vbCrLf)
        WriteToFile("        End With" & vbCrLf)
        WriteToFile("        Return True" & vbCrLf)
        WriteToFile("NotRegistered:" & vbCrLf)
        WriteToFile("        If Instring(Err.Description, " & Chr(34) & "no valid license" & Chr(34) & ") = False And noTrialThisTime = False Then" & vbCrLf)
        WriteToFile("            MsgBox(Err.Number & " & Chr(34) & ": " & Chr(34) & " & Err.Description)" & vbCrLf)
        WriteToFile("        End If" & vbCrLf)
        WriteToFile("        ActivelockValues.RegStatus = Err.Description" & vbCrLf)
        WriteToFile("        ActivelockValues.LicenceType = " & Chr(34) & "None" & Chr(34) & vbCrLf)
        WriteToFile("        If strMsg <> " & Chr(34) & Chr(34) & " Then" & vbCrLf)
        WriteToFile("            MsgBox(strMsg, MsgBoxStyle.Information)" & vbCrLf)
        WriteToFile("        End If" & vbCrLf)
        WriteToFile("        Return False" & vbCrLf)
        WriteToFile("    End Function" & vbCrLf)
        WriteToFile(vbCrLf)
    End Sub

End Module
